### ISSUE TITLE
Allow EdgeFixer plugin instead of ContinuityFixer

### ISSUE THREAD

**Issue by tvasenin** [JustinTArthur/vsfieldkit#2]
Currently there's no release of ContinuityFixer plugin that works with vsfieldkit.
Also, according to the author, EdgeFixer should be used instead:
https://github.com/MonoS/VS-ContinuityFixer/issues/2

**Comment by JustinTArthur** [comment]
Will take a look. Thanks!

**Comment by JustinTArthur** [comment]
Give vsfieldkit 1.0.2 a try if you have the EdgeFixer plugin, @tvasenin. Thanks for the report!

**Comment by tvasenin** [comment]
I confirm `v1.0.2` fixes the issue, thanks!

Could you pls upload WHL in order to be able to update VSRepo DB?
