### ISSUE TITLE
Release WHL for v1.0.2

### ISSUE THREAD

**Issue by tvasenin** [JustinTArthur/vsfieldkit#3]
We need WHL in order to be able to update via VSRepo GUI (in particular, useful for portable setup)?

**Comment by JustinTArthur** [comment]
Thanks for the heads up! I wonder why it didn't upload to PyPI.

**Comment by JustinTArthur** [comment]
Fixed. Looks like I poorly placed a wildcard in my `twine` command line. Thanks for reporting.

For vsrepo, I'm not sure whether or not we should go ahead and mark fillborders and one of the continuity/edge fixer plugins as being required given they are needed for only one of the functions. Open to ideas there.

**Comment by tvasenin** [comment]
> For vsrepo, I'm not sure whether or not we should go ahead and mark fillborders and one of the continuity/edge fixer plugins as being required given they are needed for only one of the functions. Open to ideas there.

I suggest this:
1. Leave only one of **Continuity/EdgeFixer** plugins (since both of them are released with the required changes). Probably it's better to stick to EdgeFixer and wait for the next release (recently it was converted to APIv4).
2. Mark all required plugins as hard dependencies.
